apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-container
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Alexno9/k8s-argo-minio.git'
    path: helm-charts/notebook-container
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
      name: 'in-cluster'
      namespace: notebook
      server: ''
  syncPolicy:
    automated:
      prune: true
      selfHeal: true